---
- hosts: localhost
  become: true
  gather_facts: true


  tasks:
    - name: Install alacritty terminal
      community.general.zypper:
        name: ['alacritty',
          'alacritty-zsh-completion']
        state: present
        update_cache: true
      when: ansible_distribution == "openSUSE Tumbleweed"

    - name: Install themese for alacritty
      become: false
      ansible.builtin.git:
        repo: https://github.com/alacritty/alacritty-theme
        dest: ~/.config/alacritty/themes

    - name: Place alacritty configuration file
      become: false
      ansible.builtin.template:
        src: template/alacritty.j2
        dest: ~/.config/alacritty/alacritty.yml
        mode: 0640
