---
- hosts: nvim:localhost
  gather_facts: true
  ignore_errors: true

  tasks:
    - name: Install neovim in MacOSX
      homebrew:
        name: neovim
        state: present
      when: ansible_distribution == "MacOSX"

    - name: Make a copy of previous config files
      copy:
        src: ~/.config/nvim
        dest: ~/.config/nvim.bk
        remote_src: true
        validate: ls ~/.config/nvim %s
      when: ansible_distribution == "Ubuntu"

    - name: Make a copy of previous shared config files
      copy:
        src: ~/.local/share/nvim
        dest: ~/.local/share/nvim.bk
        remote_src: true
        validate: ls ~/.local/share/nvim %s
      when: ansible_distribution == "Ubuntu"

    - name: Install Packer
      git:
        repo: 'https://github.com/wbthomason/packer.nvim'
        dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
      when: ansible_distribution == "MacOSX"

    - name: Git clone AstroNvim
      git:
        repo: 'https://github.com/AstroNvim/AstroNvim'
        dest: ~/.config/nvim

    - name: Make an user directory
      file:
        path: ~/.config/nvim/lua/user
        state: directory
        mode: '0775'

    - name: Copy nvchad statusbar config file
      copy:
        src: astronvim/status_bar.lua
        dest: ~/.config/nvim/lua/user/init.lua
        mode: '0664'

    - name: Do following after installing nvim and AstroNvim
      debug:
        msg:
          - Now run "nvim +PackerSync".
          - From inside nvim run ":Mason" to install plugins.
          - For example, ":LspInstall pyright", ":TSInstall python"
          - For debug, ":DapInstall python"
          - More, Install: black, autoflake, flake8, gitlint,
          - python-lsp-server, debugpy etc from ":Mason"
