---
- hosts: nvim
  gather_facts: yes
  ignore_errors: yes

  tasks:
    - name: Make a copy of previous config files
      copy:
        src: ~/.config/nvim
        dest: ~/.config/nvim.bk
        remote_src: yes
        validate: ls ~/.config/nvim %s
      when: ansible_distribution == "Ubuntu"

    - name: Make a copy of previous shared config files
      copy:
        src: ~/.local/share/nvim
        dest: ~/.local/share/nvim.bk
        remote_src: yes
        validate: ls ~/.local/share/nvim %s
      when: ansible_distribution == "Ubuntu"

    - name: Git clone AstroNvim
      git:
        repo: 'https://github.com/AstroNvim/AstroNvim'
        dest: ~/.config/nvim

    - name: Make an user directory
      file:
        path: ~/.config/nvim/lua/user
        state: directory
        mode: '0775'

    - name: Copy nvchad statusbar config file
      copy:
        src: astronvim/status_bar.lua
        dest: ~/.config/nvim/lua/user/init.lua
        mode: '0664'

    - name: Do following after installing nvim and AstroNvim
      debug:
        msg:
        - Now run "nvim +PackerSync".
        - From inside nvim run ":Mason" to install plugins.
        - For example, ":LspInstall pyright", ":TSInstall python"
        - For debug, ":DapInstall python"
        - More, Install: black, autoflake, flake8, gitlint,
        - python-lsp-server, debugpy etc from ":Mason"
