---
- hosts: localhost:compute:laptops
  become: true
  gather_facts: yes
  ignore_errors: true

  tasks:
    - name: Install common tools in MacOS
      macports:
        name:
          [
            "fd",
            "rsync",
            "alacritty",
            "tmux",
            "neovim",
            "git-delta",
            "ripgrep",
            "bat",
            "lsd",
            "topgrade",
            "procs",
            "skim",
            "dust",
            "tealdeer",
            "zoxide",
            "monolith",
            "sd",
          ]
        state: present
        selfupdate: yes
      when: ansible_distribution == "MacOSX"

    - name: Install common tools in Opensuse
      zypper:
        name:
          [
            "fd",
            "rsync",
            "neovim",
            "zoxide",
            "git-delta",
            "ripgrep",
            "git",
            "lazygit",
          ]
        state: present
        update_cache: yes
      when: ansible_os_family == "Suse"

    - name: Install common tools in Debian
      apt:
        name:
          [
            "rsync",
            "neovim",
            "zoxide",
            "ripgrep",
            "git",
            "python3-venv",
            "rustc",
            "python-dev-is-python3",
            "xclip",
            "xsel",
          ]
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
