---
- hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    - name: Install common tools in MacOS
      macports:
        name: [ 'fd',
          'zoxide',
          'git-delta'
          ]
        state: present
        selfupdate: yes
      when: ansible_distribution == "MacOSX"
