---
- hosts: localhost:compute
  become: true
  gather_facts: yes

  tasks:
    - name: Install common tools in MacOS
      macports:
        name: [ 'fd',
          'alacritty',
          'tmux',
          'neovim',
          'git-delta',
          'ripgrep',
          'bat',
          'lsd',
          ]
        state: present
        selfupdate: yes
      when: ansible_distribution == "MacOSX"

    - name: Install common tools in Opensuse
      zypper:
        name: [ 'fd',
          'neovim',
          'zoxide',
          'git-delta',
          'ripgrep',
          'git',
          'lazygit'
          ]
        state: present
        update_cache: yes
      when: ansible_os_family == "Suse"
