---
- hosts: localhost:compute
  become: true
  gather_facts: yes
  ignore_errors: true

  tasks:
    - name: Install common tools in MacOS
      macports:
        name: [ 'fd',
          'alacritty',
          'tmux',
          'neovim',
          'git-delta',
          'ripgrep',
          'bat',
          'lsd',
          'topgrade',
          'procs',
          'skim',
          'dust',
          'tealdeer',
          'zoxide',
          'monolith',
          'sd'
          ]
        state: present
        selfupdate: yes
      when: ansible_distribution == "MacOSX"

    - name: Install common tools in Opensuse
      zypper:
        name: [ 'fd',
          'neovim',
          'zoxide',
          'git-delta',
          'ripgrep',
          'git',
          'lazygit'
          ]
        state: present
        update_cache: yes
      when: ansible_os_family == "Suse"

    - name: Install common tools in Debian
      apt:
        name: [
          'neovim',
          'zoxide',
          'ripgrep',
          'git',
          ]
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
