---
- hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    - name: Install git-delta in MacOS
      macports:
        name: git-delta
        state: present
        selfupdate: yes
      when: ansible_distribution == "MacOSX"

    - name: Add settings in gitconfig file
      become: false
      blockinfile:
        path: ~/.gitconfig
        block: |
          [core]
            whitespace=fix          
            pager = delta

          [interactive]
            diffFilter = delta --color-only

          [delta]
            side-by-side = true
            navigate = true
            light = false
            line-numbers = true

          [merge]
            conflictstyle = diff3

          [diff]
            colorMoved = default

          [color]
            ui = auto
