---
- hosts: i3:localhost:laptops
  become: true
  gather_facts: true
  ignore_errors: true

  tasks:
    - name: Install i3 in opensuse
      community.general.zypper:
        name: [ "i3", "dmenu", "i3status", "rofi" ]
        state: present
        update_cache: true
      when: ansible_os_family == "SUSE"
      tags: pkg

    - name: Install i3 in debian varient
      ansible.builtin.apt:
        name: ["i3", "i3-wm", "xorg", "lightdm"]
        state: present
        update_cache: true
      when: ansible_distribution == "Debian" or
        ansible_distribution == "Ubuntu"
      tags: pkg

    - name: Install i3 in freebsd varient
      pkgng:
        name: ["i3", "i3status", "i3lock", "dmenu", "slim", "slim-themes", "xorg"]
        state: present
      when: ansible_os_family == "FreeBSD"
      tags: pkg

    - name: create dot config directory
      become: false
      file:
        path: ~/.config/i3
        mode: "0755"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: true

    - name: Copy i3 config
      become: false
      template:
        src: template/i3_config.j2
        dest: ~/.config/i3/config
        mode: "0644"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: install some additional packages in debian
      ansible.builtin.apt:
        name:
          [
            "konsole",
            "foliate",
            "firefox-esr",
            "neovim",
            "thunar",
            "tmux",
            "git",
            "curl",
            "lua5.4",
            "snapd",
          ]
        state: present
        update_cache: true
      when: ansible_distribution == "Debian" or
        ansible_distribution == "Ubuntu"
      tags: pkg

    - name: install some additional packages in freebsd
      pkgng:
        name:
          [
            "konsole",
            "firefox-esr",
            "falkon",
            "alacritty",
            "neovim",
            "thunar",
            "tmux",
            "git",
            "curl",
            "lua54",
          ]
        state: present
      when: ansible_os_family == "FreeBSD"
      tags: pkg

    - name: install some vga drivers in freebsd
      pkgng:
        name:
          [
            "xf86-video-intel",
            "xf86-video-vesa",
          ]
        state: present
      when: ansible_os_family == "FreeBSD"
      tags: pkg

    - name: enable slim in freebsd
      community.general.sysrc:
        name: "{{ item }}"
        value: "YES"
      with_items:
        - slim_enable
        - dbus_enable
      when: ansible_os_family == "FreeBSD"

    - name: start service in freebsd
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - dbus
        - slim
      when: ansible_os_family == "FreeBSD"
