---
- hosts: lua:localhost
  become: true
  gather_facts: true

  tasks:
    - name: Install lua in macosx
      macports:
        name: [ 'lua51',
          'lua-luacheck',
          'lua51-luarocks',
          'lua-filesystem',
          'lua-argparse',
          'lua51-luaposix',
          'lua51-ansicolor' ]

        selfupdate: true
        state: present
        update_cache: yes
      when: ansible_distribution == 'MacOSX'

    - name: Install lua in rpm based systems
      yum:
        name: [ 'lua',
          'lua-filesystem',
          'lua-devel',
          'lua-guestfs',
          'lua-http',
          'lua-json',
          'lua-lunit',
          'lua-lxc',
          'lua-posix',
          'lua-prelude',
          'lua-readline',
          'lua-sec',
          'lua-socket',
          'lua-term',
          'luarocks'
          ]
        state: present
        update_cache: true
      when: ansible_os_family == "RedHat"

    - name: Install lua in debian based systems
      apt:
        name: ['liblua5.1-0-dev',
          'liblua5.1-0',
          'lua5.1',
          'lua5.1-doc',
          'lua5.2',
          'lua5.2-doc',
          'lua-posix',
          'lua-socket',
          'lua-system',
          'lua-penlight',
          'lua-penlight-dev',
          'lua-curl',
          'luarocks',
          'luajit2',
          'lua-http',
          'lua-filesystem',
          'lua-argparse',
          'lua-check' ]
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Install lua in opensuse
      zypper:
        name: ['lua51',
          'lua51-argparse',
          'lua51-cjson',
          'lua51-devel',
          'lua51-luaposix',
          'lua51-luasocket',
          'lua51-luafilesystem',
          'lua51-luasystem',
          'lua51-penlight',
          'lua51-luarocks',
          'lua51-luacheck' ]
        state: present
        update_cache: true
      when: ansible_distribution == "openSUSE Tumbleweed"
