---
- hosts: localhost:compute:lxds

  tasks:
  - name: install tmux
    become: true
    package:
      name: [ 'tmux',
        ]
      state: latest

  - name: set tmux config file
    copy:
      src: tmux.conf
      dest: ~/.tmux.conf

  - name: git clone tmux plugins
    git:
      repo: 'https://github.com/tmux-plugins/tpm'
      dest: ~/.tmux/plugins/tpm
