---
- hosts: localhost:compute:incus:laptops
  ignore_errors: true
  vars:
    the_user: "{{ ansible_user_id }}"

  tasks:
  - name: install zsh and others packages in MacOS
    become: true
    macports:
      name: [ 'zsh',
        'curl',
        'git',
        ]
      state: present
      update_cache: true
    when: ansible_os_family == "Darwin"

  - name: install zsh and others packages in MacOS
    become: true
    package:
      name: [ 'zsh',
        'curl',
        'git',
        ]
      state: present
      update_cache: true
    when: ansible_os_family != "Darwin"

  - name: change user shell to zsh
    become: true
    user:
      name: "{{ the_user }}"
      shell: /bin/zsh

  - name: set zshrc file
    template:
      src: template/zshrc.j2
      dest: ~/.zshrc
    tags: zshrc

  - name: set p10k file
    copy:
      src: p10k.zsh
      dest: ~/.p10k.zsh
