---
- hosts: localhost:compute:incus:laptops
  ignore_errors: true
  vars:
    the_user: "{{ ansible_user_id }}"

  tasks:
    - name: get infos of all installed packages
      ansible.builtin.package_facts:

    - name: install zsh and others packages in MacOS
      become: true
      macports:
        name: ["zsh", "curl", "git"]
        state: present
        update_cache: true
      when: ansible_os_family == "Darwin"

    - name: install zsh and others packages in other than MacOS
      become: true
      package:
        name: ["zsh", "curl", "git"]
        state: latest
      when: ansible_os_family != "Darwin"

    - name: change user shell to zsh
      become: true
      user:
        name: "{{ the_user }}"
        shell: /usr/bin/zsh
      when: ( ansible_os_family != "Darwin"
        and ansible_os_family != "FreeBSD" )
        and ( 'zsh' in ansible_facts.packages )

    - name: change user shell to zsh in freebsd
      become: true
      user:
        name: "{{ the_user }}"
        shell: /usr/local/bin/zsh
      when: ansible_os_family == "FreeBSD"
        and ('zsh' in ansible_facts.packages )

    - name: set zshrc file
      template:
        src: template/zshrc.j2
        dest: ~/.zshrc
      tags: zshrc

    - name: set p10k file
      copy:
        src: p10k.zsh
        dest: ~/.p10k.zsh
