---
name: Install neovim

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible ansible-lint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        #- name: Lint with ansible-lint
        #run: |
        #ansible-lint neovim.yml
    - name: Install neovim
      run: |
        ansible-playbook neovim.yml -l localhost
